#!/bin/bash


RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

rm -f $USER-submission.zip

make clean && make >> compileErrors.txt

if [[ $? -ne 0 ]]; then
    echo -e "${RED}Code did not compile"
    echo -e "${RED}Errors are located in compileErrors.txt"
    echo -e "${NC}"
    exit 1
fi

make clean

rm ./compileErrors.txt

test -f "./Makefile"
if [[ $? -ne 0 ]]; then
    echo -e "${RED}No Makefile. Please create a file called Makefile that compiles your code"
    echo -e "${NC}"
    exit 1
fi

zip -r USER-submission.zip ./src ./Makefile ./googletest override.token
echo -e "${GREEN}Zip file successfully created"
echo -e "${GREEN}Rename USER-submission with your username (for example, lukebeukelman-submission), then submit to gradescope for the coresponding deliverable"
echo -e "${NC}"
exit 0

